version: '3'
services:
  python:
    build: .
    image: dzmitry/mogiminsk:${GIT_HASH:-latest}
    ports:
      - "8090:8090"
    environment:
      - SENTRY_DSN=$SENTRY_DSN
      - SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${DB_DATABASE:-postgres}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - TELEGRAM_API_KEY=$TELEGRAM_API_KEY
      - VIBER_API_KEY=$VIBER_API_KEY
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - VIBER_TOKEN=$VIBER_TOKEN
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-central-1"
        awslogs-group: "mogiminsk"
        awslogs-stream: "mogiminsk-python"
        awslogs-create-group: "true"


  postgres:
    image: "postgres:9.6"
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - mogiminsk.dzmitry.psql:/var/lib/postgresql/data
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-central-1"
        awslogs-group: "mogiminsk"
        awslogs-stream: "mogiminsk-postgres"
        awslogs-create-group: "true"

volumes:
  mogiminsk.dzmitry.psql: