version: "3"
services:
  python:
    build: .
    image: dzmitry/mogminsk
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - VIBER_API_KEY=${VIBER_API_KEY}
      - VIBER_TOKEN=${VIBER_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
    volumes:
      - .:/app:ro

  postgres:
    image: "postgres:9.6.10-alpine"
    volumes:
      - mogminskbot.pgsql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  mogminskbot.pgsql: