version: "3"
services:
  python:
    build: .
    image: dzmitry/mogminsk
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - VIBER_API_KEY=${VIBER_API_KEY}
      - VIBER_TOKEN=${VIBER_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - POSTGRESS_HOST=${POSTGRESS_HOST}
      - POSTGRESS_PORT=${POSTGRESS_PORT}
    volumes:
      - .:/app:ro
    depends_on:
      - postgres
    ports:
      - "8090:8090"

  postgres:
    image: "postgres:9.6.10-alpine"
    volumes:
      - mogminskbot.pgsql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "6432:5432"

volumes:
  mogminskbot.pgsql: