version: 2
jobs:
  build:
    docker:
     - image: circleci/python:3.7
     - image: circleci/postgres:9.6
    steps:
     - checkout

     - restore_cache:
         name: Restore venv.
         key: python3.7-v1-{{ checksum "requirements.txt" }}

     - run:
         name: Install python dependencies.
         command: |
           python3.7 -m venv env
           . env/bin/activate
           pip install -r requirements/dev.txt

     - save_cache:
         name: Save venv.
         key: python3.7-v1-{{ checksum "requirements.txt" }}
         paths:
          - env

     - run:
         name: pytest
         command: |
           . env/bin/activate
           python -m pytest

     - run:
        name: Create and upload an image to ECR.
        command: |
          docker-compose build python
          docker tag dzmitry/mogiminsk:latest ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/mogiminsk:${CIRCLE_BUILD}
          $(aws ecr get-login --no-include-email --region=eu-central-1)
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/mogiminsk:${CIRCLE_BUILD}

     - run:
        name: Deploy.
        command: |
          python3.7 ecs/step_2--build_task_definition.py > ecs/step_3--prepared.json

          # Here goes extracting of the task arn!
          aws ecs register-task-definition --cli-input-json file://ecs/step_3--prepared.json --region=eu-central-1

          aws ecs update-service --cluster mogiminsk --service dev --region=eu-central-1 --task-definition  arn:aws:ecs:eu-central-1:${AWS_ACCOUNT_ID}:task-definition/mogiminsk-madness:2

