version: 2

jobs:
  build:
   docker:
    - image: circleci/python:3.6
      environment:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: postgres
        DB_USERNAME: postgres
        DB_PASSWORD: anytemppass
        TELEGRAM_API_KEY: quite-simple-one
        VIBER_API_KEY: quite-simple-one
        TELEGRAM_TOKEN: tele:token
        VIBER_TOKEN: viber-token
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_PASSWORD: anytemppass
        POSTGRES_DB: test_postgres

   steps:
    - checkout

    - add_ssh_keys:
        fingerprints:
          - "45:a3:78:84:ed:6d:78:c8:85:ce:90:2f:90:60:8f:e1"

    - run:
        name: interaction
        command: git clone git@bitbucket.org:demidov91/mogiminsk_interaction.git mogiminsk_interaction

    - restore_cache:
         name: Restore venv.
         key: python3.6-v1-{{ checksum "requirements.txt" }}

    - run:
        name: prepare env
        command: |
          python -m venv env
          . env/bin/activate
          pip install pip-tools
          pip-sync

    - save_cache:
         name: Save venv.
         key: python3.6-v1-{{ checksum "requirements.txt" }}
         paths:
          - env

    - run: |
        . env/bin/activate
        pytest