"""phone is not unique

Revision ID: 73c9ca6b5152
Revises: d1e16f83f626
Create Date: 2019-09-16 01:24:31.392382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c9ca6b5152'
down_revision = 'd1e16f83f626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_ip_blocked_ip')
    op.drop_constraint('mogiminsk_user_phone_key', 'mogiminsk_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mogiminsk_user_phone_key', 'mogiminsk_user', ['phone'])
    op.create_table('block_ip_blocked_ip',
    sa.Column('ip', sa.VARCHAR(length=31), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ip', name='block_ip_blocked_ip_pkey')
    )
    # ### end Alembic commands ###
